import {useColorScheme} from 'react-native';

export default appColors = () => {
  const colorScheme = useColorScheme();

  return colorScheme == 'light'
    ? {
        // light Theme:
        themeRed: '#ff0000',
        greyBack: '#333333',
        white: '#fff',
        black: '#000',
        ToastSuccess: '#228B22',
        ToastInfo: '#ffcc00',
        ToastError: '#ff0000',
        ToastSuccessBack: '#e5f6df',
        ToastInfoBack: '#FFFACD',
        ToastErrorBack: '#FFCCCB',
        formError: '#cc3300',
        boldBlacktext: '#333333',
        Textlightblack: '#666666',
        TextInputborderbg: '#d3d3d3',
        placeHolderText: '#d6d6d6',
        placeHolderTextDark: '#b9b9b9',
        inputBackDark: '#111111',
        borderColor: '#e5e5e5',
        cardBack: '#f3f3f3',
        greyBg: '#f4f4f4',
        searchPlaceHolder: '#bbbbbb',
        textGrey: '#a3a2a2',
        cardbg: '#f4f4f4',
        subtotalBack: '#fef5ec',
        ratingGray: '#dbdbdb',
        overlayBg: 'rgba(0, 0, 0, 0.5)',
        overlayBgCorousel: 'rgba(0, 0, 0, 0.2)',
        themeyellowLight: '#fdecda',
        yellowDotBorder: '#fce2c7',
        yellowLine: '#fbdab7',
        lightGreyLine: '#d9d9d9',
        themeYellowDark: '#ea9a43',
        activegreen: '#06a23a',
        lightGreen: '#daf5e3',
        active: '#06a23a',
        deactive: '#f2252c',
        lightBlackBack: '#393939',
      }
    : {
        // Dark Theme:
        themeRed: '#ff0000',
        greyBack: '#333333',
        white: '#fff',
        black: '#000',
        ToastSuccess: '#228B22',
        ToastInfo: '#ffcc00',
        ToastError: '#ff0000',
        ToastSuccessBack: '#e5f6df',
        ToastInfoBack: '#FFFACD',
        ToastErrorBack: '#FFCCCB',
        formError: '#cc3300',
        boldBlacktext: '#333333',
        Textlightblack: '#666666',
        TextInputborderbg: '#d3d3d3',
        placeHolderText: '#d6d6d6',
        placeHolderTextDark: '#b9b9b9',
        inputBackDark: '#111111',
        borderColor: '#e5e5e5',
        cardBack: '#f3f3f3',
        greyBg: '#f4f4f4',
        searchPlaceHolder: '#bbbbbb',
        textGrey: '#a3a2a2',
        cardbg: '#f4f4f4',
        subtotalBack: '#fef5ec',
        ratingGray: '#dbdbdb',
        overlayBg: 'rgba(0, 0, 0, 0.5)',
        overlayBgCorousel: 'rgba(0, 0, 0, 0.2)',
        themeyellowLight: '#fdecda',
        yellowDotBorder: '#fce2c7',
        yellowLine: '#fbdab7',
        lightGreyLine: '#d9d9d9',
        themeYellowDark: '#ea9a43',
        activegreen: '#06a23a',
        lightGreen: '#daf5e3',
        active: '#06a23a',
        deactive: '#f2252c',
        lightBlackBack: '#393939',
      };
};
